name: Terraform Deployment

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select the environment'
        required: true
        default: 'prod'
        type: choice
        options:
          - prod

permissions:
  id-token: write
  contents: read
  packages: write
  pull-requests: write

jobs:
  terraform-plan:
    name: Terraform Plan
    environment: 
      name: ${{ github.event.inputs.environment }}

    env:
      TF_VAR_db_name: ${{ secrets.DB_NAME }}
      TF_VAR_db_username: ${{ secrets.DB_USERNAME }}
      TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}

    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.0

      - name: Setup up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.9.4"

      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE_ARN }}
          role-session-name: Terraform-Deployment

      - name: Check role
        run: aws sts get-caller-identity

      - name: Terraform-Plan
        working-directory: ${{ github.event.inputs.environment }}
        run: |
          terraform init
          terraform plan

  terraform-apply:
    name: Terraform Apply
    environment: 
      name: ${{ github.event.inputs.environment }}

    gh_environment:
      name: ${{ github.event.inputs.environment }}

    env:
      TF_VAR_db_name: ${{ secrets.DB_NAME }}
      TF_VAR_db_username: ${{ secrets.DB_USERNAME }}
      TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}

    runs-on: ubuntu-latest
    needs:
      - terraform-plan
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.0

      - name: Setup up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.9.4"

      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE_ARN }}
          role-session-name: Terraform-Deployment

      - name: Check role
        run: aws sts get-caller-identity

      - name: Terraform-Apply
        working-directory: ${{ github.event.inputs.environment }}
        
        run: |
          terraform init
          terraform apply --auto-approve
          # terraform destroy -auto-approve
          